'use strict';

/**
 * post service
 */

const { createCoreService } = require('@strapi/strapi').factories;

module.exports = createCoreService('api::post.post');

/** Request sent through strap are handled by routes and these routes are generated by default for all content types */